name: 'Docker Build and Deploy'

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: ECR login
        run: docker login -u AWS -p $(aws ecr get-login-password --region ap-south-1) 010928211868.dkr.ecr.ap-south-1.amazonaws.com
      - name: Docker build
        run: docker build -t 010928211868.dkr.ecr.ap-south-1.amazonaws.com/simple-nodejs:latest .
      - name: Docker push
        run: docker push 010928211868.dkr.ecr.ap-south-1.amazonaws.com/simple-nodejs:latest

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Deploy
        run: docker run -d 010928211868.dkr.ecr.ap-south-1.amazonaws.com/simple-nodejs:latest nodejs
